name: Python Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov tox flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Unit Tests with pytest
        run: |
          pytest -v --cov=./ --cov-report term-missing

      - name: Run Integration Tests
        run: |
          # Add integration test execution command here
          # Example: python -m unittest discover -s integration_tests -p "*_test.py"
          echo "Running integration tests..."
          # Replace the following line with your actual integration tests command
          python -m unittest discover -s tests/integration -p "test_*.py"

      - name: Run E2E Tests
        run: |
          # Add e2e test execution command here
          # Example: python -m pytest e2e_tests/
          echo "Running e2e tests..."
          # Replace the following line with your actual e2e tests command
          python -m pytest tests/e2e